# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

install:
  - pip install tox coveralls pytest-travis-fold
  - TOX_ENV=$(python -c "import sys;print('py{}{}'.format(*sys.version_info[:2]))")
script: tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
after_success:
  - coveralls